### ISSUE TITLE
Warning message loop

### ISSUE THREAD

**Issue by oriolroger** [backdrop-contrib/mandrill#2]
Hi, we've noticed that every time a Mandrill error is fired to Watchdog, a new Warning message is created everytime we visit the Watchdog page (message "`Notice: Array to string conversion in check_plain()`").

That's because when throwing the Mandrill error, is trying to write the recipient with variable `$message['to']`, and that variable is not a string, but an array.

We think the variable should change to `$message['to'][0]['email']`, so the whole call to watchdog should be like this:

```
  catch (Mandrill_Error $e) {
    watchdog('mandrill', 'Error sending email from %from to %to. @code: @message',
      array(
        '%from' => $message['from_email'],
        '%to' => $message['to'][0]['email'],
        '@code' => $e->getCode(),
        '@message' => $e->getMessage(),
      ),
      WATCHDOG_ERROR
    );
    return FALSE;
  }
```

**Comment by argiepiano** [comment]
Hi @oriolroger and thanks for reporting. This module doesn't have a maintainer. Wondering if you might be interested? Otherwise, would you provide a PR for this, and have the @backdrop-contrib/bug-squad merge it.

**Comment by oadaeh** [comment]
The code for this module is quite old. The fix for this was committed to the D7 counterpart back in Apr 11, 2019:
- https://www.drupal.org/project/mandrill/issues/2316731#comment-12099309
- https://git.drupalcode.org/project/mandrill/-/commit/f209ce14aedee05635d457516b99d0c2a24d5ba7

It also includes fixes for sending to CCed and BCCed recipients.

I don't know if it will apply without the commits that happened before it, but it's worth a shot.

**Comment by indigoxela** [comment]
Closing for now, as we just switched to a different branch with lots of fixes from Drupal.

Feel free to reopen, if the new branch also shows the problem.
